-- Explore All objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

-- Explore All Countries our customers come from 
SELECT DISTINCT country FROM gold.dim_customers

-- Explore All Categories "The Major Divisions"
SELECT DISTINCT category FROM gold.dim_product

SELECT DISTINCT category , subcategory , product_name FROM gold.dim_product
ORDER BY 1,2,3

-- Find the date of the first and last order
SELECT 
MIN(order_date) AS first_order_date ,
MAX(order_date) AS last_order_date ,
DATEDIFF(year , MIN(order_date) , MAX(order_date)) AS order_range_year,
DATEDIFF(month , MIN(order_date) , MAX(order_date)) AS order_range_month
FROM gold.fact_sales

-- Find the youngest and the oldest customer 
SELECT 
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year, MIN(birthdate) , GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year , MAX(birthdate) , GETDATE()) AS youngest_age
FROM gold.dim_customers


-- Find the Total Sales 
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold 
SELECT  SUM(quntity) AS total_quantity FROM gold.fact_sales 

-- Find the avarage selling price 
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the total number of orders 
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales 
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

-- Find the total number of products 
SELECT COUNT(product_key) AS total_products FROM gold.dim_product

-- Find the total number of customers 
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customer FROM gold.dim_customers

-- Generate a report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_value, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quntity) AS measure_value FROM gold.fact_sales

-- Find total customers by countries 
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC


-- Find total customers by gender 
SELECT 
	gender,
	COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY gender 
ORDER BY total_customer DESC


-- Find total products by category 
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_product
GROUP BY category
ORDER BY total_products DESC


-- What is the average costs in each category ? 
SELECT 
	category,
	AVG(cost) AS avg_costs
FROM gold.dim_product
GROUP BY category
ORDER BY avg_costs DESC


-- What is the total revenue generated for each category ? 
SELECT 
	p.category,	
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_product p ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC


-- What is the total revenue generated by each customer ? 
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c ON c.customer_id = f.customer_id
GROUP BY 
	c.customer_key ,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC


-- What is the distribution of sold items across countries ? 
SELECT 
	c.country,
	SUM(f.quntity) AS total_sold_items
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c ON c.customer_id = f.customer_id
GROUP BY 
	c.country
ORDER BY total_sold_items DESC


-- Which 5 products generate the highest revenue ? 
SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_product p ON p.product_key = f.product_key
GROUP BY p.product_name 
ORDER BY total_revenue DESC


-- What are the 5 worst - performing products in terms of sales ? 
SELECT * 
FROM (
	SELECT
		p.product_name,
		SUM(f.sales_amount) AS total_revenue,
		RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales f 
	LEFT JOIN gold.dim_product p ON p.product_key = f.product_key
	GROUP BY p.product_name
)t 
WHERE rank_products <= 5 


-- Find the top 10 customers who have generated the highest revenue 
SELECT TOP 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c ON c.customer_id = f.customer_id
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- The 3 customers with the fewest order placed
SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c ON c.customer_id = f.customer_id
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_orders 
